services:
  db:
    container_name: mysql_products
    restart: always
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_TCP_PORT=3307
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=products
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: